---
title: "Project Proposal"
output: html_notebook
---

## Section 1. Introduction
#### The introduction should introduce your general research topic and your data (where it came from, how it was collected, what are the cases, what are the variables, etc.).
Our topic focuses on popular Walt Disney World attractions. In this data, we explore ride wait times 
and the affect that certain enviornmental conditions have on the duration of these wait times. We collected 
this data through researching Walt Disney World's data on wait times and ticket sales. Our data originated 
from the raw dataset: https://touringplans.com/walt-disney-world/crowd-calendar#DataSetsv
Data is largely continuous across time with the exception of gaps in ride service.
The variables studied in this data include local schools in session, park capacity, holidays, weather conditions, 
as well as the opening and closing time of the park. Not all variables are used in our analysis.


## Section 2. Data Analysis Plan
From the given datasets, we decided to create our own dataframes that focus on variables including weather, parade times, 
attraction wait times, splash aspect of ride, and whether the ride and its line is indoor or outdoor.
We aim to explore the affects of weather conditions on wait times for popular Disney World rides.

- Does hot weather increase wait times for rides with a "Splash_Aspect"?
- Does rainy weather cause an increase in wait times for "indoor rides"?
- Determine the busiest Day of week, Month, and Year (lubridate data) for tourists to visit WDW
- Fireworks and parade times as well as sunset times
- Create a structed travel plan for tourists to minimize the amount of time spent waiting in line

## Section 3. Data
#### Data Description
#### Print out a glimpse of the data frame. In your project repo: place your data in the /data folder, and add the data dictionary and source for the dataset to the README.md file in the /data folder. Make sure the codebook is neatly formatted and easy to read.
The data here is a huge mess because it's the raw metadata from touringplans.com. Specific ride data is each in its own file.

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
Disney_Data <- read_csv("../data/metadata.csv")
glimpse(Disney_Data)
```
