---
title: "est_time_box_plot.rmd"
output: html_notebook
---

```{r}
library(tidyverse)
library(reshape2)
library(lubridate)
library(forcats)
```

```{r}
head(rides_df)
```


```{r}
for (i in 1:14) {
  mean <- rides[[i]] %>%
    summarise(mean = mean(SPOSTMIN, na.rm=T)) %>%
    round(digits = 2)
  print(paste("The average wait time for ", names(rides[i]), " is ", mean, sep = ""))
}
```


```{r}
for (i in 1:14) {
  mean <- rides[[i]] %>%
    summarise(mean = mean(SACTMIN, na.rm=T)) %>%
    round(digits = 2)
  print(paste("The real average wait time for ", names(rides[i]), " is ", mean, sep = ""))
}
```


```{r}
rides_df %>%
  filter(datetime > as.POSIXct("2018-06-30")) %>%
  ggplot(aes(x = SPOSTMIN, y = ride_name)) +
  geom_boxplot(na.rm = TRUE, outlier.shape = "circle", outlier.alpha = .1, size = 1) + 
  coord_cartesian(xlim = c(0,275)) +
  geom_vline(xintercept = c(30, 60, 90, 120), color = c("green", "yellow", "orange", "red"), size = 1) +
  labs(title = "Boxplot of mean estimated wait time by ride") +
  xlab("Wait time in minutes") +
  ylab("Ride name")
```


```{r}
rides_df %>% group_by(ride_name) %>%
  filter(datetime > as.POSIXct("2018-06-30")) %>%
  ggplot(aes(x = SACTMIN, y = ride_name)) +
  geom_boxplot(na.rm = TRUE, outlier.shape = "circle", outlier.alpha = .1, size = 1) +
  coord_cartesian(xlim = c(0, 200)) +
  geom_vline(xintercept = c(30, 60, 90, 120), color = c("green", "yellow", "orange", "red"), size = 1) +
  labs(title = "Boxplot of mean user wait time by ride") +
  xlab("Wait time in minutes") +
  ylab("Ride name")
```


```{r}
park_averages <- rides_df %>%
  inner_join(ride_metadata) %>%
  group_by(park) %>%
  summarise(park_averages = mean(SPOSTMIN, na.rm = TRUE))
rides_df %>%
  inner_join(ride_metadata) %>%
  mutate(weekday = weekdays(datetime)) %>%
  group_by(ride_name, park) %>%
  summarise(mean_wait = mean(SPOSTMIN, na.rm = TRUE)) %>%
  ggplot() +
  geom_col(aes(x = park, y = mean_wait, fill = ride_name), position = "dodge") +
  labs(title = "Column chart of mean estimated wait time by ride, grouped by park", fill = "Ride name") +
  xlab("Park (Animal Kingdom, Epcot, Hollywood Studios, Magic Kingdom)") +
  ylab("Mean wait (minutes)")
```


```{r}
rides_df %>%
  mutate(weekday = weekdays(datetime)) %>%
  group_by(weekday, ride_name) %>%
  summarise(mean_wait = mean(SPOSTMIN, na.rm = TRUE)) %>%
  ggplot() +
  geom_col(aes(x = ordered(weekday, levels = days_of_week), y = mean_wait)) +
  labs(title = "Mean estimated wait time by day for each ride") +
  xlab("Day of the week") +
  ylab("Mean wait (minutes)") +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap(~ ride_name)
```


```{r}
rides_df %>%
  mutate(weekday = weekdays(datetime)) %>%
  group_by(weekday, ride_name) %>%
  summarise(mean_wait = mean(SPOSTMIN, na.rm = TRUE)) %>%
  ggplot(aes(x = ordered(weekday, levels = days_of_week), y = mean_wait, fill = ride_name)) +
  geom_col() +
  labs(title = "Mean combined estimated wait time by day of week") +
  xlab("Day of the week") +
  ylab("Mean wait (minutes)")
```


```{r}
rides_df %>%
  inner_join(ride_metadata) %>%
  mutate(weekday = weekdays(datetime)) %>%
  group_by(weekday, park) %>%
  summarise(mean_wait = mean(SPOSTMIN, na.rm = TRUE)) %>%
  ggplot() +
  geom_col(aes(x = ordered(weekday, levels = days_of_week), y = mean_wait, fill = park), position = "fill") +
  labs(title = "Mean estimated wait time by park as a portion of total wait time by day", fill = "Park") +
  xlab("Day of the week") +
  ylab("Portion of total wait time")
```


```{r}
rides_df %>%
  mutate(year = year(as.POSIXct(mdy(date) + 1)), month = month(as.POSIXct(mdy(date) + 1)), day = weekdays(as.POSIXct(mdy(date) + 1)),
         monthweek = ceiling(day(mdy(date)) / 7)) %>%
  group_by(month, day, monthweek) %>%
  summarise(mean_wait = mean(SPOSTMIN, na.rm = TRUE)) %>% 
  ggplot(aes(x = monthweek, y = ordered(day, levels = rev(days_of_week)), fill = mean_wait)) +
  geom_tile(color = "grey") +
  facet_wrap(~month) +
  #scale_fill_gradient2(low = "blue", mid = "orange", high = "red", midpoint = 60) +
  scale_fill_distiller(palette = "Spectral") +
  labs(fill = "Wait (min)", title = "Mean wait time by day of the year for all rides", x = "Week of the month", y = "")
```


```{r}
rides_df %>%
  mutate(year = year(as.POSIXct(mdy(date) + 1)), month = month(as.POSIXct(mdy(date) + 1)), day = wday(as.POSIXct(mdy(date) + 1)),
         monthweek = ceiling(day(mdy(date)) / 7)) %>%
  group_by(month, day, monthweek) %>%
  summarise(mean_wait = mean(SPOSTMIN, na.rm = TRUE)) %>% 
  ggplot(aes(x = monthweek, y = ordered(day, levels = days_of_week), fill = mean_wait)) +
  geom_tile(color = "grey") +
  facet_grid(~month) +
  #scale_fill_gradient2(low = "blue", mid = "orange", high = "red", midpoint = 60) +
  scale_fill_distiller(palette = "Spectral") +
  labs(fill = "Wait (min)", title = "Mean wait time by week of the year for all rides", x = "Week of the month", y = "")
```

