---
title: "fix_rides.rmd"
output: html_notebook
---

Load libraries
```{r}
library(tidyverse)
library(lubridate)
library(hms)
```


```{r}
dwarfs_train <- read_csv("../data/7_dwarfs_train.csv")
alien_saucers <- read_csv("../data/alien_saucers.csv")
dinosaur <- read_csv("../data/dinosaur.csv")
expedition_everest <- read_csv("../data/expedition_everest.csv")
flight_of_passage <- read_csv("../data/flight_of_passage.csv")
kilimanjaro_safaris <- read_csv("../data/kilimanjaro_safaris.csv")
navi_river <- read_csv("../data/navi_river.csv")
pirates_of_caribbean <- read_csv("../data/pirates_of_caribbean.csv")
rock_n_rollercoaster <- read_csv("../data/rock_n_rollercoaster.csv")
slinky_dog <- read_csv("../data/slinky_dog.csv")
soarin <- read_csv("../data/soarin.csv")
spaceship_earth <- read_csv("../data/spaceship_earth.csv")
splash_mountain <- read_csv("../data/splash_mountain.csv")
toy_story_mania <- read_csv("../data/toy_story_mania.csv")

head(dwarfs_train)
```


```{r}
rides <- list("dwarfs_train" = dwarfs_train, 
              "alien_saucers" = alien_saucers,
              "dinosaur" = dinosaur,
              "expedition_everest" = expedition_everest,
              "flight_of_passage" = flight_of_passage,
              "kilimanjaro_safaris" = kilimanjaro_safaris,
              "navi_river" = navi_river,
              "pirates_of_caribbean" = pirates_of_caribbean,
              "rock_n_rollercoaster" = rock_n_rollercoaster,
              "slinky_dog" = slinky_dog,
              "soarin" = soarin,
              "spaceship_earth" = spaceship_earth,
              "splash_mountain" = splash_mountain,
              "toy_story_mania" = toy_story_mania)

head(rides[1])
```

# Can we make this faster?
```{r}
for (i in 1:14) {
  rides[[i]] <- rides[[i]] %>%
    mutate(time = format(ymd_hms(datetime), "%H:%M:%S"))
  rides[[i]] <- rides[[i]] %>%
    mutate(ride_name = as.factor(names(rides[i])))
}

head(rides[[1]])
```


Remove rows with -999 as the estimated wait time
```{r}
for (i in 1:14) {
  rides[[i]] <- rides[[i]] %>%
     filter(SPOSTMIN != -999 | is.na(SPOSTMIN))
}

head(rides[[1]])
```


# Rides that have a splash aspect:
```{r}
#This code has been replaced by the next chunk
if (FALSE) {
splash <- c("pirates_of_caribbean", "splash_mountain", "flight_of_passage")
indoor <- c("dinosaur", "flight_of_passage", "navi_river", "pirates_of_caribbean", 
            "rock_n_rollercoaster", "soarin", "spaceship_earth", "toy_story_mania")
for (i in 1:14) {
  if (names(rides[i]) %in% splash) {
    rides[[i]] <- rides[[i]] %>%
    mutate(splash = TRUE)
  } else {
    rides[[i]] <- rides[[i]] %>%
    mutate(splash = FALSE)
  }
  if (names(rides[i]) %in% indoor) {
    rides[[i]] <- rides[[i]] %>%
    mutate(indoor = TRUE)
  } else {
    rides[[i]] <- rides[[i]] %>%
    mutate(indoor = FALSE)
  }
}

head(rides[[13]])
}
```


```{r}
ride_name <- c("dwarfs_train", "alien_saucers", "dinosaur", "expedition_everest", "flight_of_passage", 
               "kilimanjaro_safaris", "navi_river", "pirates_of_caribbean", "rock_n_rollercoaster", "slinky_dog", 
               "soarin", "spaceship_earth", "splash_mountain", "toy_story_mania")
open_date <- as.POSIXct(c("2014/05/28", "2018/06/30", "1998/04/22", "2006/04/09", "2017/05/27", 
                       "1998/04/22", "2017/05/27", "1973/12/17", "1999/07/29", "2018/06/30", 
                       "2005/05/15", "1982/10/01", "1992/07/17", "2008/05/31"))
splash <- c(FALSE, FALSE, FALSE, FALSE, TRUE,
            FALSE, FALSE, TRUE,  FALSE, FALSE,
            FALSE, FALSE, TRUE,  FALSE)
indoor <- c(FALSE, FALSE, TRUE,  FALSE, TRUE,
            FALSE, TRUE,  TRUE,  TRUE,  FALSE,
            TRUE,  TRUE,  FALSE, TRUE)
age_hierarchy <- c(10, 13,  4,  8, 11,
                    5, 12,  1,  6, 14,
                    7,  2,  3,  9)
park <- c("mk", "hs", "ak", "ak", "ak", 
          "ak", "ak", "mk", "hs", "hs", 
          "ep", "ep", "mk", "hs")
ride_metadata <- data.frame(ride_name, open_date, age_hierarchy, splash, indoor, park)
ride_metadata
```

Makes a stupid big dataframe with all the rides
```{r}
rides_df <- rides[[1]]
for (i in 2:14) {
  rides_df <- rbind(rides_df, rides[[i]])
}
rides_df
```

